### PR TITLE
Update Python Client to latest API

### PR DESCRIPTION
**Pull request by marcinplata**
The PR includes:
- updated autogenerated code that incorporates our latest API version:
-- added cancel endpoint
-- added archive endpoint
-- modified list endpoint
-- modified status endpoint
-- modified fetch endpoint (handle different formats and metarig)
- several fixes of the autogenerated code (e.g. duplicated or wrong definition of body arguments)
- updated examples
- removed retopology endpoints (as it is in the API)

TESTED=Command validation:
```bash
# set credentials using:
export YELLOW_HOST=<dev_host>
export YELLOW_TOKEN=<test_user_token>

python examples/fetch_and_render_asset.py
python examples/generate_asset.py
python examples/list_generated_assets.py
```

### CODE REVIEW

**Review by johanjavierdebruin — COMMENTED** [review]
Perhaps we should add a comment in the README that this plugin is being deprecated? Besides that the changes looks good to me

**Comment by marcinplata** [comment]
> Perhaps we should add a comment in the README that this plugin is being deprecated? Besides that the changes looks good to me

Right. Added

**Review by johanjavierdebruin — APPROVED** [review]
We should probably coordinate merging these changes with our deployment of `webapp` to prod.

**Review by Cam2337 — APPROVED** [review]
This was a little difficult to review as it's quite large. A quick glance through LGTM given that we're deprecating this.

For a sanity check, could you include some `TESTED=` with some lightweight proof of using this version of the `yellow-client` to ensure it works in the PR description?

**Pull request merged**
